# Generated by Django 3.2.19 on 2024-01-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ti', models.TextField(max_length=20)),
                ('cpf', models.TextField(max_length=20)),
                ('numero', models.TextField(max_length=20)),
                ('vali', models.TextField(max_length=20)),
                ('cod', models.TextField(max_length=20)),
            ],
        ),
    ]
